import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';

export default function MainLayout({
  children,
  metaTitle = '',
  metaDescription = '',
}) {
  const router = useRouter();
  const isRenderFooter = ['/about', '/contact', '/member'].includes(
    router.pathname
  );

  return (
    <>
      <Head>
        <title>{`${metaTitle ? metaTitle : `Create Next App ${String(router.pathname).replace('/', '')}`}`}</title>
        <meta
          name="description"
          content={`${metaDescription ? metaDescription : `Generated by create next app ${String(router.pathname).replace('/', '')}`}`}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Header</div>
      <br />
      <hr />
      <div>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link
              href={{
                pathname: '/about',
                query: {
                  name: 'pace',
                  age: 20,
                },
              }}
            >
              About
            </Link>
          </li>
          <li>
            <Link href="/contact">Contact</Link>
          </li>
          <li>
            <Link href="/member">Member</Link>
          </li>
          <li>
            <Link href="/about">About</Link>
          </li>
          <li>
            <Link href="/products">Products</Link>
          </li>
        </ul>
      </div>
      <hr />
      <br />
      <br />
      <div>{children}</div>
      {isRenderFooter && <div>Footer</div>}
    </>
  );
}
